[package]
name = "rice-golomb"
version = "0.2.0"
edition = "2024"
authors = ["Heliax AG"]
license = "MIT"
description = "A small Rust library for Rice-Golomb coding, a form of entropy coding used in lossless compression."
repository = "https://github.com/heliaxdev/rice-golomb"
readme = "README.md"
keywords = ["compression", "entropy", "golomb", "rice", "encoding"]
categories = ["compression", "encoding", "algorithms"]

[dependencies]
bitvec = "1.1.1"

[dev-dependencies]
vers-vecs = { version = "1", features = ["serde"] }
bincode = "1"
tiny-varint = "0.2"
rand = "0.9"
